class_to_index = {
   "pedestrian"            :  0  ,
   "bicyclist"             :  1  ,
   "motorcyclist"          :  2  ,
   "rider_other"           :  3  ,
   "bird"                  :  4  ,
   "cat"                   :  5  ,
   "dog"                   :  6  ,
   "horse"                 :  7  ,
   "sheep"                 :  8  ,
   "cow"                   :  9  ,
   "elephant"              :  10 ,
   "bear"                  :  11 ,
   "zebra_animal"          :  12 ,
   "giraffe"               :  13 ,
   "car"                   :  14 ,
   "truck"                 :  15 ,
   "trailer"               :  16 ,
   "bus"                   :  17 ,
   "train"                 :  18 ,
   "motorcycle"            :  19 ,
   "bicycle"               :  20 ,
   "van"                   :  21 ,
   "caravan"               :  22 ,
   "wheeled_slow"          :  23 ,
   "vehicle_other"         :  24 ,
   "boat"                  :  25 ,
   "plane"                 :  26 ,
   "ship"                  :  27 ,
   "ego_vehicle"           :  28 ,
   "car_mount"             :  29 ,
   "sky_other"             :  30 ,
   "ground"                :  31 ,
   "mud"                   :  32 ,
   "playing_field"         :  33 ,
   "hill"                  :  34 ,
   "mountain"              :  35 ,
   "land"                  :  36 ,
   "sand"                  :  37 ,
   "grass"                 :  38 ,
   "gravel"                :  39 ,
   "rock"                  :  40 ,
   "field"                 :  41 ,
   "tree"                  :  42 ,
   "flower"                :  43 ,
   "palm"                  :  44 ,
   "potted_plant"          :  45 ,
   "sea"                   :  46 ,
   "river"                 :  47 ,
   "lake"                  :  48 ,
   "water_other"           :  49 ,
   "waterfall"             :  50 ,
   "snow"                  :  51 ,
   "skyscraper"            :  52 ,
   "house"                 :  53 ,
   "roof"                  :  54 ,
   "hovel"                 :  55 ,
   "tower"                 :  56 ,
   "door"                  :  57 ,
   "window"                :  58 ,
   "curtain"               :  59 ,
   "window_blind"          :  60 ,
   "building"              :  61 ,
   "bridge"                :  62 ,
   "tunnel"                :  63 ,
   "tent"                  :  64 ,
   "pier"                  :  65 ,
   "column"                :  66 ,
   "phone_booth"           :  67 ,
   "stairway"              :  68 ,
   "steps"                 :  69 ,
   "stair"                 :  70 ,
   "escalator"             :  71 ,
   "fountain"              :  72 ,
   "ceiling_other"         :  73 ,
   "grandstand"            :  74 ,
   "awning"                :  75 ,
   "tank"                  :  76 ,
   "canopy"                :  77 ,
   "swimming_pool"         :  78 ,
   "wall_brick"            :  79 ,
   "wall_other"            :  80 ,
   "wall_stone"            :  81 ,
   "wall_tile"             :  82 ,
   "wall_wood"             :  83 ,
   "fence"                 :  84 ,
   "railing"               :  85 ,
   "bannister"             :  86 ,
   "bike_lane"             :  87 ,
   "parking"               :  88 ,
   "rail_track"            :  89 ,
   "road"                  :  90 ,
   "crosswalk_plain"       :  91 ,
   "zebra"                 :  92 ,
   "marking_other"         :  93 ,
   "manhole"               :  94 ,
   "pothole"               :  95 ,
   "service_lane"          :  96 ,
   "floor_other"           :  97 ,
   "wood_floor"            :  98 ,
   "pavement"              :  99 ,
   "curb_cut"              :  100,
   "curb"                  :  101,
   "floor_stone"           :  102,
   "pedestrian_area"       :  103,
   "runway"                :  104,
   "dirt_track"            :  105,
   "path"                  :  106,
   "catch_basin"           :  107,
   "pole"                  :  108,
   "utility_pole"          :  109,
   "street_light"          :  110,
   "light_other"           :  111,
   "lamp"                  :  112,
   "chandelier"            :  113,
   "sconce"                :  114,
   "traffic_light"         :  115,
   "broccoli"              :  116,
   "carrot"                :  117,
   "food_other"            :  118,
   "fruit"                 :  119,
   "banana"                :  120,
   "apple"                 :  121,
   "orange"                :  122,
   "sandwich"              :  123,
   "hot_dog"               :  124,
   "pizza"                 :  125,
   "donut"                 :  126,
   "cake"                  :  127,
   "cabinet"               :  128,
   "bed"                   :  129,
   "desk_stuff"            :  130,
   "table"                 :  131,
   "dining_table"          :  132,
   "snooker_table"         :  133,
   "coffee_table"          :  134,
   "seat"                  :  135,
   "chair"                 :  136,
   "swivel_chair"          :  137,
   "sofa"                  :  138,
   "armchair"              :  139,
   "ottoman"               :  140,
   "stool"                 :  141,
   "shelf"                 :  142,
   "wardrobe"              :  143,
   "dresser"               :  144,
   "bookcase"              :  145,
   "cradle"                :  146,
   "mirror"                :  147,
   "vitrine"               :  148,
   "nightstand"            :  149,
   "kitchen_island"        :  150,
   "toilet"                :  151,
   "bath"                  :  152,
   "shower_curtain"        :  153,
   "screen_door"           :  154,
   "countertop"            :  155,
   "buffet"                :  156,
   "counter"               :  157,
   "radiator"              :  158,
   "hood"                  :  159,
   "sink"                  :  160,
   "fireplace"             :  161,
   "base"                  :  162,
   "stage"                 :  163,
   "bar"                   :  164,
   "picture"               :  165,
   "fan"                   :  166,
   "arcade_machine"        :  167,
   "conveyer_belt"         :  168,
   "bench"                 :  169,
   "fire_hydrant"          :  170,
   "trashcan"              :  171,
   "billboard"             :  172,
   "traffic_sign_front"    :  173,
   "traffic_sign_back"     :  174,
   "traffic_sign_frame"    :  175,
   "banner"                :  176,
   "bulletin_board"        :  177,
   "trade_name"            :  178,
   "poster"                :  179,
   "mailbox"               :  180,
   "parking_meter"         :  181,
   "bike_rack"             :  182,
   "junction_box"          :  183,
   "cctv_camera"           :  184,
   "sculpture"             :  185,
   "barrel"                :  186,
   "snowboard"             :  187,
   "kite"                  :  188,
   "baseball_bat"          :  189,
   "baseball_glove"        :  190,
   "skateboard"            :  191,
   "surfboard"             :  192,
   "tennis_racket"         :  193,
   "frisbee"               :  194,
   "skis"                  :  195,
   "teddy_bear"            :  196,
   "ball"                  :  197,
   "refridgerator"         :  198,
   "stove"                 :  199,
   "oven"                  :  200,
   "microvawe"             :  201,
   "dishwasher"            :  202,
   "washer"                :  203,
   "toaster"               :  204,
   "clothes"               :  205,
   "tie"                   :  206,
   "plate"                 :  207,
   "bottle"                :  208,
   "drinking_glass"        :  209,
   "cup"                   :  210,
   "fork"                  :  211,
   "knife"                 :  212,
   "spoon"                 :  213,
   "bowl"                  :  214,
   "pot"                   :  215,
   "vase"                  :  216,
   "tray"                  :  217,
   "handbag"               :  218,
   "backpack"              :  219,
   "suitcase"              :  220,
   "mouse"                 :  221,
   "keyboard"              :  222,
   "laptop"                :  223,
   "computer_screen"       :  224,
   "monitor"               :  225,
   "crt_screen"            :  226,
   "tv"                    :  227,
   "screen"                :  228,
   "cardboard"             :  229,
   "rug"                   :  230,
   "paper"                 :  231,
   "pillow"                :  232,
   "cushion"               :  233,
   "towel"                 :  234,
   "book"                  :  235,
   "scissors"              :  236,
   "toothbrush"            :  237,
   "box"                   :  238,
   "remote"                :  239,
   "cell_phone"            :  240,
   "hair_drier"            :  241,
   "basket"                :  242,
   "net"                   :  243,
   "umbrella"              :  244,
   "flag"                  :  245,
   "clock"                 :  246,
   "blanket"               :  247,
   "autorickshaw"          :  248,
   "drivable_fallback"     :  249,
   "polegroup"             :  250,
   "fallback_background"   :  251,
   "dirt"                  :  252,
   "whiteboard"            :  253,
   "carpet_floor"          :  254,
   "pickup"                :  255,
   "mobilebarrier"         :  256,
   "otherprop"             :  257,
   "otherstructure"        :  258,
   "trash"                 :  259,
   "pole_tl"               :  260,
   "ignore"                :  261,
    }


